[book]
authors = [
  "The Real-Time Interrupt-driven Concurrency developers",
  "Emil Fresk <emil.fresk@gmail.com>",
  "Henrik Tj√§der <henrik@tjaders.com>",
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
multilingual = false
src = "src"
title = "Real-Time Interrupt-driven Concurrency"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.wavedrom]
command = "mdbook-wavedrom"

[output.html]
git-repository-url = "https://github.com/rtic-rs/cortex-m-rtic"
git-repository-icon = "fa-github"
additional-js = ["mermaid.min.js", "mermaid-init.js", "wavedrom.min.js", "wavedrome-default.js"]
