[book]
authors = [
  "The Real-Time Interrupt-driven Concurrency developers",
  "Emil Fresk <emil.fresk@gmail.com>",
  "Henrik Tj√§der <henrik@tjaders.com>",
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
src = "src"
title = "Real-Time Interrupt-driven Concurrency"

[build]
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/rtic-rs/rtic"
git-repository-icon = "fab-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
