language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - binutils-arm-none-eabi

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - binutils-arm-none-eabi

    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - binutils-arm-none-eabi

    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - binutils-arm-none-eabi

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
