[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["concurrency", "embedded", "no-std"]
description = "Procedural macros of the cortex-m-rtfm crate"
documentation = "https://japaric.github.io/cortex-m-rtfm/api/cortex_m_rtfm"
edition = "2018"
keywords = ["arm", "cortex-m"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rtfm-macros"
readme = "../README.md"
repository = "https://github.com/japaric/cortex-m-rtfm"
version = "0.4.0"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.10"
proc-macro2 = "0.4.24"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "0.15.23"

[dependencies.rand]
default-features = false
version = "0.5.5"

[features]
timer-queue = []