[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "cortex-m-rtfm-macros"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
quote = "0.3.15"
rtfm-syntax = "0.1.0"
syn = "0.11.11"

[lib]
proc-macro = true
